apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key | upper }}: {{ $val | b64enc | quote }}
  {{- end }}